on: pull_request

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iffy/install-nim@v5.1.1
        with:
          version: stable
      - run: nim build
      - run: ./package_scanner packages.json --check-pr --check-urls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
